services:
    backend:
        build: backend
        restart: unless-stopped
        depends_on:
            - database
        ports:
            - 3000:3000

    database:
        container_name: tennis_database
        image: postgres:17.0
        restart: unless-stopped
        env_file:
            - project.env

    database-migrations:
        image: flyway/flyway:10
        env_file:
            - project.env
        depends_on:
            - database
        volumes:
            - ./database-migrations:/flyway/sql
        command: -connectRetries=60 -baselineOnMigrate=true migrate

    swagger-ui:
        image: docker.swagger.io/swaggerapi/swagger-ui
        ports:
            - 8080:8080
        environment:
            - SWAGGER_JSON=/swagger-docs/swagger.json
        volumes:
            - ./swagger-docs:/swagger-docs
        depends_on:
            - backend
